(()=>{const KEY="mi-entrenamiento-v1";let data=[];let selectedDate=null;let deferredPrompt=null;
const $=id=>document.getElementById(id), pad=n=>String(n).padStart(2,"0");
const key=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const today=new Date(), todayKey=key(today);
const parse=s=>{const [y,m,d]=s.split("-").map(Number);return new Date(y,m-1,d)};
const fmt=s=>parse(s).toLocaleDateString("es-CL",{weekday:"long",day:"numeric",month:"long"});
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
try{data=JSON.parse(localStorage.getItem(KEY)||"[]");if(!Array.isArray(data))data=[]}catch{data=[]}
$("today").textContent=fmt(today);$("date")?.setAttribute("value",todayKey);

function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function render(){renderToday();renderHistory();renderCalendar();renderStats()}
function renderToday(){const rs=data.filter(x=>x.date===todayKey);$("todayCount").textContent=`${rs.length} ejercicio${rs.length===1?"":"s"}`;const vol=rs.reduce((a,x)=>a+x.sets*x.reps*x.weight,0);$("sessionVolume").textContent=vol?`${Math.round(vol)} kg de volumen`:"";const box=$("todayExercises");box.innerHTML=rs.length?"":"<div class='card mutedBox'>Aún no has registrado ejercicios hoy.</div>";rs.forEach(addRow)}
function addRow(r){const box=$("todayExercises"),el=document.createElement("div");el.className="exerciseRow";el.innerHTML=`<div><div class="name">${esc(r.exercise)}</div><div class="meta">${r.sets} × ${r.reps}${r.weight?" · "+r.weight+" kg":""}${r.notes?" · "+esc(r.notes):""}</div></div><button class="delete" type="button">Eliminar</button>`;el.querySelector("button").onclick=()=>{data=data.filter(x=>x.id!==r.id);save();render()};box.appendChild(el)}
function renderHistory(){const box=$("historyList");box.innerHTML="";const groups={};[...data].sort((a,b)=>b.date.localeCompare(a.date)||b.id-a.id).forEach(r=>(groups[r.date]??=[]).push(r));if(!Object.keys(groups).length){box.innerHTML="<div class='card mutedBox'>No hay registros todavía.</div>";return}Object.entries(groups).forEach(([date,rs])=>{const g=document.createElement("div");g.className="dateGroup";g.innerHTML=`<div class="dateTitle">${esc(fmt(date))}</div><div class="list"></div>`;box.appendChild(g);const list=g.querySelector(".list");rs.forEach(r=>{const el=document.createElement("div");el.className="exerciseRow";el.innerHTML=`<div><div class="name">${esc(r.exercise)}</div><div class="meta">${r.sets} × ${r.reps}${r.weight?" · "+r.weight+" kg":""}</div></div><button class="delete" type="button">×</button>`;el.querySelector("button").onclick=()=>{data=data.filter(x=>x.id!==r.id);save();render()};list.appendChild(el)})})}
function renderCalendar(){const y=today.getFullYear(),m=today.getMonth(),first=new Date(y,m,1),days=new Date(y,m+1,0).getDate(),offset=(first.getDay()+6)%7; $("monthLabel").textContent=first.toLocaleDateString("es-CL",{month:"long",year:"numeric"});const grid=$("calendarGrid");grid.innerHTML="";for(let i=0;i<offset;i++)grid.appendChild(document.createElement("div"));for(let d=1;d<=days;d++){const dt=new Date(y,m,d),k=key(dt),rs=data.filter(x=>x.date===k),el=document.createElement("button");el.type="button";el.className=`day ${rs.length?"has":""} ${k===todayKey?"today":""}`;el.innerHTML=`<b>${d}</b><small>${rs.length?rs.length+" ej.":" "}</small>`;el.onclick=()=>showDay(k);grid.appendChild(el)}}
function showDay(k){selectedDate=k;const rs=data.filter(x=>x.date===k);$("selectedDay").innerHTML=`<strong>${esc(fmt(k))}</strong>${rs.length?`<div style="margin-top:9px">${rs.map(r=>`<div style="padding:6px 0;border-bottom:1px solid var(--border)"><b>${esc(r.exercise)}</b><br><small>${r.sets} × ${r.reps}${r.weight?" · "+r.weight+" kg":""}</small></div>`).join("")}</div>`:"<p style='margin:8px 0 0'>No hay ejercicios registrados.</p>"}`}
function renderStats(){const days=new Set(data.map(x=>x.date));$("statDays").textContent=days.size;$("statExercises").textContent=data.length;$("statSets").textContent=data.reduce((a,x)=>a+x.sets,0);$("statVolume").textContent=Math.round(data.reduce((a,x)=>a+x.sets*x.reps*x.weight,0))+" kg";const counts={};data.forEach(x=>counts[x.exercise]=(counts[x.exercise]||0)+1);const top=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,6),box=$("topExercises");box.innerHTML=top.length?"":"<p class='mutedBox'>Todavía no hay datos.</p>";const max=top[0]?.[1]||1;top.forEach(([n,c])=>{const row=document.createElement("div");row.className="barRow";row.innerHTML=`<div><div style="font-size:13px;font-weight:650">${esc(n)}</div><div class="barBg"><div class="bar" style="width:${c/max*100}%"></div></div></div><b>${c}</b>`;box.appendChild(row)});const tips=[];if(!data.length)tips.push("Empieza registrando incluso sesiones cortas: lo importante es crear el hábito.");else{if(days.size<2)tips.push("Intenta repartir tus sesiones durante la semana en vez de concentrarlas todas en un solo día.");else tips.push(`Llevas ${days.size} días de entrenamiento registrados. Busca una frecuencia que puedas mantener.`);tips.push("Cuando completes tus repeticiones con buena técnica y el ejercicio se sienta cómodo, considera una progresión gradual de peso o repeticiones.");tips.push("Registra el peso cuando puedas: así podremos observar tu progreso real con el tiempo.");tips.push("El descanso y la recuperación también son parte del entrenamiento. Si aparece dolor, no lo fuerces.");}$("advice").innerHTML=tips.map(t=>`<div class="tip">💡 ${esc(t)}</div>`).join("")}
$("exerciseForm").addEventListener("submit",e=>{e.preventDefault();const exercise=$("exercise").value.trim(),sets=Number($("sets").value),reps=Number($("reps").value),weight=Math.max(0,Number($("weight").value)||0);if(!exercise||sets<1||reps<1){$("formMsg").textContent="Revisa el ejercicio, series y repeticiones.";return}data.push({id:Date.now(),date:todayKey,exercise,sets,reps,weight,notes:$("notes").value.trim()});save();$("exercise").value="";$("notes").value="";$("formMsg").textContent="✓ Guardado";setTimeout(()=>$("formMsg").textContent="",1500);render()});
$("clearAll").onclick=()=>{if(confirm("¿Borrar todo el historial? Esta acción no se puede deshacer.")){data=[];save();render()}};
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".view").forEach(x=>x.classList.add("hidden"));b.classList.add("active");$(b.dataset.view).classList.remove("hidden")});
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;$("installBtn").classList.remove("hidden")});
$("installBtn").onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();deferredPrompt=null;$("installBtn").classList.add("hidden")};
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js").catch(()=>{}));
render();
})();